# general settings
# name: UDA4CAC_davqsft_uda_s3_udatrans_lsfa1e-2unetlsd1e-1_ganonboth1e-2_vlsd_bs8_200k_PSNR_a4d_flsganweight1e-2_wfrozenVQGANcycle_benchmarktrue_seed0_noclamp
name: OmniLens_AODLibpretrain_SwinIR_DAmodel_bs8
# model_type: PureCycleVQModel
# model_type: FeMaSRModel_FA
model_type: DAModel
# model_type: CycleVQModel
scale: 1
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Lib
    type: UDADataset
    dataroot_gt: datasets/AODLib-EAOD/Imgs/gt
    dataroot_lq: datasets/AODLib-EAOD/Imgs/train
    dataroot_trg: path/your_specificdata/train

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~



  val_0:
    name: specific
    type: PairedImageDataset
    dataroot_gt: path/your_specificdata/val_gt
    dataroot_lq: path/your_specificdata/val
    io_backend:
      type: disk


network_g:
  type: SwinIRv2
  upscale: 1
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  shuffle: True
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: pixelshuffle
  resi_connection: 1conv

# path
path:
  pretrain_network_g: pretrain/pretrained/SwinIR_AODLib_EAOD.pth
  strict_load_g: true
  param_key_g: params_ema 
  resume_state: ~

# training settings 
train:
  optim_g:
    type: Adam
    lr: !!float 1e-6
    weight_decay: 0
    betas: [0.9, 0.99]


  scheduler:
    type: MultiStepLR
    milestones: [200000, 250000, 300000, 350000]
    # milestones: [30000, 40000, 50000, 100000]
    gamma: 1.0

  total_iter: 20000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0 
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 1.0





  trgtv_opt:
    type: TVLoss
    loss_weight: !!float 0.00
  trgdc_opt:
    type: DarkChannelLoss
    window_size: 15
    weight: !!float 0.05



  net_d_iters: 1
  net_d_init_iters: !!float 0 

# validation settings·
val:
  val_freq: !!float 1e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    lpips: # metric name, can be arbitrary
      type: calculate_lpips
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
