# general settings
name: OmniLens_AODLibpretrain_SwinIR_specificmodel_fewshotspecific_bs8
model_type: SwinIRModel
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: specific_train
    type: PairedImageDataset
    dataroot_gt: path/your_specificdata/train_gt
    dataroot_lq: path/your_specificdata/train
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_0:
    name: specific_val
    type: PairedImageDataset
    dataroot_gt: path/your_specificdata/val_gt
    dataroot_lq: path/your_specificdata/val
    io_backend:
      type: disk



# network structures
# network_g:
network_g:
  type: SwinIRv2
  upscale: 1
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  shuffle: True
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: pixelshuffle
  resi_connection: 1conv

# path
path:
  pretrain_network_g: pretrain/pretrained/SwinIR_AODLib_EAOD.pth
  strict_load_g: true
  param_key_g: params_ema 
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 160000, 180000, 190000]
    gamma: 1.0

  total_iter: 10000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    lpips: # metric name, can be arbitrary
      type: calculate_lpips
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
